import numpy as np
a=np.arange(6)
b=np.array([0,1,2,3,4])
c=np.array([6,1,1,1,1])
print(a)
print('')
print(a.sum())
print('')
print(a.mean(),b.mean(),c.mean())
print('')
print(a.std(),b.std(),c.std())
print('')
print(a.min())
print('')
print(a.max())