import numpy as np
a=np.array([[1,2,3,4],[4,5,6,7]])
b=np.random.randint(1,3,8).reshape(2,4)

print(a)
print(' ')
print(b)
print('')
print(a*b)
print('')
c=np.array([1,2]).reshape(2,1)
print(c)
print('')
print(a*c)
print('')
d=np.array([1,1,1,1])
print(a+d)
e=np.array([1,2]).reshape(1,2)
print(e)
print('')
# print(a*e)